#!/bin/bash
if cat $1.txt | grep mp4; then
  tail -1 $1.txt | xargs aria2c --max-connection-per-server 16 -s 16 -l aria2.log --user-agent '$useragent' -o $2.mp4
fi
if cat $1.txt | grep mp3; then
  tail -1 $1.txt | xargs aria2c --max-connection-per-server 16 -s 16 -l aria2.log --user-agent '$useragent' -o $2.mp3
fi
if cat $1.txt | grep webm; then
  tail -1 $1.txt | xargs aria2c --max-connection-per-server 16 -s 16 -l aria2.log --user-agent '$useragent' -o $2.webm
fi
