#!/bin/bash
useragent='Mozilla/5.0 (compatible)'
curl -Ls -A '$useragent' -o - $1 | # -> Request html from the link pass by param
grep videoplayback |                           # -> Find the line of javascript with params of the video
sed 's/,/\n/g' |                               # -> New line where has a comma, make each array param a single line
grep url_encoded_fmt_stream_map |              # -> Find the line with direct video urls
sed 's/\\u0026/\n/g' |                         # -> New line on a char especial wich divide urls details
tee >(grep type= > yturls.txt) |
grep url= |                                    # -> Find the url in itsel
xargs -0 echo -e $(sed 's/%/\\x/g') |          # -> Convert hex chars to string
sed 's/url=//g; s/.*"url_encoded_fmt_stream_map":"//' >> yturls.txt
